FROM fabric8/java-alpine-openjdk8-jdk
ENV JAVA_APP_JAR hello-microprofile-thorntail.jar
ENV AB_OFF true
ENV JAEGER_SERVICE_NAME hello-microprofile
ADD target/hello-microprofile-thorntail.jar /deployments/